### PR TITLE
add coveralls task

### PR DESCRIPTION
**Pull request by pon**

### CODE REVIEW

**Comment by leore** [comment]
LGTM

**Comment by pon** [comment]
Can you see if you can get it to work in coveralls? I tried to add the repo but nothing comes up

**Comment by leore** [comment]
https://coveralls.io/r/lob/hapi-bookshelf-models

it wasnt added to coveralls. Should work now

**Comment by pon** [comment]
Cool - that was the part I couldn't get to work. Wouldn't show up in the list on coveralls.io

**Pull request merged**
