### PR TITLE
Fixed error thrown by a configuration with a relative path to models

### PR DESCRIPTION
**Pull request by derbaeuerle**
I pushed a new commit on my fork to fix the issue #20.

### CODE REVIEW

**Comment by robinjoseph08** [comment]
@derbaeuerle Thanks for the fix! LGTM!

We recently added the [`generate-changelog`](https://github.com/lob/generate-changelog#usage) module to this repo so that we don't have to worry about manually creating the changelog. We'll be updating the README so that it's more clear when contributing, but until then, can you amend your commit message to follow the format?

```
fix(paths): fixed error thrown by a configuration with a relative path to models
```

**Comment by slester** [comment]
I can also do this if @derbaeuerle is unavailable? Thanks!

**Comment by robinjoseph08** [comment]
Not sure, but it's fine by me. If you want to fix the message @slester, I'll happily merge and publish a new version!

**Comment by robinjoseph08** [comment]
Thanks for doing the work to get a fix for this @derbaeuerle. @slester put up another PR with your fixes with a fixed commit message so now the fix has been released in version 1.7.1.

**Pull request closed without merging**
